INSERT INTO AREA(nome) VALUES('INFORMÁTICA');
INSERT INTO AREA(nome) VALUES('AGROPECUÁRIA');
INSERT INTO AREA(nome) VALUES('QUÍMICA');
SELECT * FROM AREA;livro
SELECT * FROM LIVRO;
SELECT * FROM USUARIO;